name: Build Immich armv7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/arm/v7
          outputs: type=docker,dest=/tmp/immich-armv7.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immich-armv7
          path: /tmp/immich-armv7.tar
